### ISSUE TITLE
MissingPluginException in iOS

### ISSUE THREAD

**Issue by DineshKachhot** [mwaylabs/flutter-apns#46]
iOS is giving following exception while initialising firebase,

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
<asynchronous suspension>
#1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
#2      MethodChannel.invokeListMethod
package:flutter/…/services/platform_channel.dart:345
#3      MethodChannelFirebase._initializeCore
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:30
#4      MethodChannelFirebase.initializeApp
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:75
#5      Firebase.initializeApp
package:firebase_core/src/firebase.dart:43
#6      main
package:Rastrack/main.dart:260
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:11<…>

```

Pub versions:
flutter_apns: ^1.4.1
firebase_core: ^0.7.0

**Comment by andzejsw** [comment]
Same issue for me, but with firebase_core: ^0.5.1

**Comment by andzejsw** [comment]
Ok. Readme file helped with this one. I jut added these lines in Info.plist file:
```
<key>flutter_apns.disable_firebase_core</key>
<false/>
```

**Comment by szotp** [comment]
@DineshKachhot hope that solution worked for you as well.
